spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/sstest
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.SQL: debug

#jwt ??
jwt:
  header: Authorization
  secret: 723005cb7684713295353925f622b579a14b4a1519a04574c7db8f5074f522e6f9d2b1d517b2d647c510463c2942d7b8905b07b2f5ad88a77d9529b32d5d93cd
  token-validity-in-seconds: 86400